app = "myapp-fashion"
primary_region = "nrt"

[build]

[env]
  RAILS_ENV = "production"
  RAILS_SERVE_STATIC_FILES = "true"
  RAILS_LOG_TO_STDOUT = "true"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[checks]
  [checks.status]
    grace_period = "30s"
    interval = "15s"
    method = "GET"
    path = "/up"
    port = 3000
    timeout = "10s"
    type = "http" 